### ISSUE TITLE
More helpful type validation error

### ISSUE THREAD

**Issue by lexicalunit** [vlas-voloshin/JSONSchemaValidation#5]
The parse error is not ambiguous, but it could be more useful.

Example error message:

```
schema validation failure: Error Domain=com.argentumko.JSONSchemaValidationError Code=300 "JSON instance validation against the schema failed." UserInfo=0x7fa1c963a2a0 {validator=<VVJSONSchemaTypeValidator: 0x7fa1c96366d0>{ types: boolean }, NSLocalizedDescription=JSON instance validation against the schema failed., object=1} {
    NSLocalizedDescription = "JSON instance validation against the schema failed.";
    object = 1;
    validator = "<VVJSONSchemaTypeValidator: 0x7fa1c96366d0>{ types: boolean }";
}
```

Desired error message:

```
schema validation failure: Error Domain=com.argentumko.JSONSchemaValidationError Code=300 "JSON instance validation against the schema failed." UserInfo=0x7fa1c963a2a0 {validator=<VVJSONSchemaTypeValidator: 0x7fa1c96366d0>{ types: boolean }, NSLocalizedDescription=JSON instance validation against the schema failed., object=1} {
    NSLocalizedDescription = "JSON instance validation against the schema failed.";
    object = 1;
    property = the_property_whose_value_failed_to_validate_goes_here;
    validator = "<VVJSONSchemaTypeValidator: 0x7fa1c96366d0>{ types: boolean }";
}
```

**Comment by vlas-voloshin** [comment]
Yes, I agree – the errors definitely could use some more details. It's something I was actually planning to do, but didn't just because I haven't been looking for improvements for some time now. I'll try implementing this soon-ish. Thanks for your suggestion!

**Comment by lexicalunit** [comment]
Thanks! The error message we actually encounter nearly every day is the  additional properties not allowed error. We spend a lot of time tracking down and double checking lists of properties trying to find what we've accidentally added, or it could be caused by a typo too. Very easy validation error to get, and very hard to diagnose without knowing which properties are causing the validation failure.

### Example error message

<VVJSONSchemaObjectPropertiesValidator: 0x7ffbaaf1dba0>{ 57 properties; additional properties: not allowed; 0 pattern properties }

### Desired error message

<VVJSONSchemaObjectPropertiesValidator: 0x7ffbaaf1dba0>{ 57 properties; additional properties: not allowed; 0 pattern properties; invalid properties: list, of, properties, that, cause, validation, failure }

**Comment by vlas-voloshin** [comment]
I've updated the library to include two new parameters in the error object:
– `path` – contains the full path to the failed object in a form of JSON Pointer. An empty path means that the root-level object failed validation.

**Comment by lexicalunit** [comment]
(Insert radical guitar solo here) You rock! Thanks! I'll check this out later this week when I'm back at work. This is going to save a lot of our engineers are lot of time :+1:

**Comment by vlas-voloshin** [comment]
I'll close this issue for now due to lack of activity. Feel free to reopen it or create a new issue if necessary.
